version: '3.7'

services:
  pg:
    image: bitnami/postgresql:11-debian-9
    container_name: pg
    environment:
      POSTGRESQL_USERNAME: root
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_DATABASE: dev
    ports:
      - '5436:5432'
    networks:
      - backend
  pg-test:
    image: bitnami/postgresql:11-debian-9
    container_name: pg-test
    environment:
      POSTGRESQL_USERNAME: root
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_DATABASE: test
    ports:
      - '5438:5432'
    networks:
      - backend
  queue:
    image: redis
    platform: linux/amd64
    ports:
      - "6399:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
